app:
  # Apollo 中的 AppId
  id: sc-discovery-server

apollo:
  # apollo dev环境的 meta 地址，即config service 的 URL
  meta: http://10.28.21.213:8881
  bootstrap:
    # 启用启动期加载
    enabled: true
    # 需要加载的命名空间
    namespaces: application.yml